version: "3"
services:
  backend:
    build: .
    environment:
      - MONGODB_CONNSTRING=mongodb://cent:kanayo@mongodb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
  frontend:
    build: ./client
    ports:
      - 4000:3000
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cent
      - MONGO_INITDB_ROOT_PASSWORD=kanayo
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
